# Generated by Django 2.1.4 on 2019-04-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
